let keysArray = [
  "ce",
  "c",
  "delete",
  "history",
  "sin",
  "cos",
  "tan",
  "ln",
  "log",
  "arcSin",
  "arcCos",
  "arcTan",
  "10powX",
  "epowX",
  "xpow2",
  "percentage",
  "sqrt",
  "powY",
  "rtY",
  "pie",
  "n-factorial",
  "(",
  ")",
  "plusOrMinus",
  "7",
  "8",
  "9",
  "4",
  "5",
  "6",
  "1",
  "2",
  "3",
  ".",
  "0",
  "equals",
  "+",
  "-",
  "/",
  "*",
];
//control keys
let controlarr = ["ce", "c", "delete", "history"];

// dom elements definations
let resultBlock = document.querySelector(".result-block"),
  textInputBlock = document.querySelector(".text-input-block"),
  historyBlock = document.querySelector(".history-block"),
  controlKeys = document.querySelector(".control-keys"),
  scientificKeys = document.querySelector(".scientific-keys"),
  numerals = document.querySelector(".numerals"),
  operators = document.querySelector(".operators"),
  equalsKey = document.querySelector(".equals"),
  menuButton = document.querySelector(".toggle-click-div"),
  themeButton = document.querySelector(".theme-div p"),
  cancelEverythingKey = controlKeys.children[0],
  cancelKey = controlKeys.children[1],
  deleteKey = controlKeys.children[2],
  historyKey = controlKeys.children[3],
  clearHistoryButton = document.querySelector(".clear-history"),
  backToCalculation = document.querySelector(".back-to-calculation"),
  Ntxt = document.querySelector(".normal-txt"),
  Stxt = document.querySelector(".scientific-txt"),
  Ctxt = document.querySelector(".conversion-txt"),
  calculationKeys_parentNode = document.querySelector(".keys"),
  modeList = document.querySelector(".mode-list"),
  themeList = document.querySelector(".theme-list"),
  partOne = document.querySelector(".part-one"),
  partTwo = document.querySelector(".part-two"),
  normalModeButton = document.querySelector(".mode-list").children[0],
  scientificModeButton = document.querySelector(".mode-list").children[1],
  conversionModeButton = document.querySelector(".mode-list").children[2],
  mainTag = document.getElementsByTagName("main")[0],
  lightThemeButton = document.querySelector(".theme-list").children[0],
  darkThemeButton = document.querySelector(".theme-list").children[1],
  normalThemeButton = document.querySelector(".theme-list").children[2],
  noHistoryBox = document.querySelector(".no-history"),
  historyControlBox = document.querySelector(".history-control"),
  resultContainer = document.querySelector(".result-container"),
  historyContent = document.querySelector(".history-container");

export {
  resultBlock,
  textInputBlock,
  historyBlock,
  controlKeys,
  scientificKeys,
  numerals,
  operators,
  equalsKey,
  menuButton,
  themeButton,
  themeList,
  cancelEverythingKey,
  cancelKey,
  deleteKey,
  historyKey,
  clearHistoryButton,
  backToCalculation,
  Ntxt,
  Stxt,
  Ctxt,
  keysArray,
  controlarr,
  calculationKeys_parentNode,
  modeList,
  partOne,
  partTwo,
  normalModeButton,
  scientificModeButton,
  conversionModeButton,
  mainTag,
  lightThemeButton,
  normalThemeButton,
  darkThemeButton,
  noHistoryBox,
  historyControlBox,
  resultContainer,
  historyContent,
};
